export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE';
export const GET_STYLES = 'GET_STYLES';

export const GET_REVIEWS = 'GET_REVIEWS';
export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS';
export const GET_REVIEWS_FAILURE = 'GET_REVIEWS_FAILURE';

export const GET_REVIEWS_META = 'GET_REVIEWS_META';
export const GET_REVIEWS_META_SUCCESS = 'GET_REVIEWS_META_SUCCESS';
export const GET_REVIEWS_META_FAILURE = 'GET_REVIEWS_META_FAILURE';