export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE';
export const GET_PRODUCT = 'GET_PRODUCT';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE';
export const GET_STYLES = 'GET_STYLES';
export const GET_STYLES_SUCCESS = 'GET_STYLES_SUCCESS';
export const GET_STYLES_FAILURE = 'GET_STYLES_FAILURE';

export const GET_REVIEWS = 'GET_REVIEWS';
export const GET_REVIEWS_SUCCESS = 'GET_REVIEWS_SUCCESS';
export const GET_REVIEWS_FAILURE = 'GET_REVIEWS_FAILURE';
<<<<<<< HEAD

export const GET_REVIEWS_META = 'GET_REVIEWS_META';
export const GET_REVIEWS_META_SUCCESS = 'GET_REVIEWS_META_SUCCESS';
export const GET_REVIEWS_META_FAILURE = 'GET_REVIEWS_META_FAILURE';
=======
>>>>>>> 6b311aeacceeca57d730dbfb49d46065e2784040
